# Generated by Django 5.2 on 2025-05-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employer_id', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(default=0)),
                ('title', models.CharField(choices=[('Technology', 'Technology'), ('Networking', 'Networking'), ('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Content Writing', 'Content Writing'), ('Customer Support', 'Customer Support'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Design', 'Design'), ('Education', 'Education')], max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('work_hours', models.DecimalField(choices=[(1, '1-10 hours'), (2, '11-20 hours'), (3, '21-30 hours'), (4, '31-40 hours'), (5, '40+ hours')], decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('remote', 'Remote'), ('hibrid', 'Hibrid'), ('internship', 'Internship'), ('contractual', 'Contractual')], max_length=100)),
                ('requirements', models.TextField()),
                ('educational_level', models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD')], max_length=20)),
                ('experience_level', models.CharField(choices=[('entry_level', 'Entry Level (0-2 years)'), ('mid_level', 'Mid Level (3-5 years)'), ('senior_level', 'Senior Level (5+ years)')], max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('requirements', models.TextField(max_length=10000)),
                ('responsibilities', models.TextField(max_length=10000)),
                ('location', models.CharField(max_length=100)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Techjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('requirements', models.CharField(blank=True, max_length=100)),
                ('responsibilities', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null='True')),
                ('email', models.EmailField(max_length=254, null='True')),
                ('password', models.CharField(max_length=100, null='True')),
                ('confirm_password', models.CharField(max_length=100, null='True')),
            ],
        ),
    ]
