# Generated by Django 5.2 on 2025-05-14 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('linkedin_profile', models.URLField(blank=True, max_length=100)),
                ('portfolio_website', models.URLField(blank=True, max_length=100)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(default=0)),
                ('title', models.CharField(choices=[('Technology', 'Technology'), ('Networking', 'Networking'), ('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Content Writing', 'Content Writing'), ('Customer Support', 'Customer Support'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Design', 'Design'), ('Education', 'Education')], max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.CharField(choices=[('<20000', 'Less than 20,000'), ('20000-40000', '20,000 - 40,000'), ('40000-60000', '40,000 - 60,000'), ('60000-80000', '60,000 - 80,000'), ('80000-100000', '80,000 - 100,000'), ('>100000', 'More than 100,000')], max_length=100)),
                ('status', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('remote', 'Remote'), ('hibrid', 'Hibrid'), ('internship', 'Internship'), ('contractual', 'Contractual')], max_length=100)),
                ('work_hours', models.IntegerField(choices=[(1, '1-10 hours'), (2, '11-20 hours'), (3, '21-30 hours'), (4, '31-40 hours'), (5, '40+ hours')])),
                ('requirements', models.TextField(max_length=400)),
                ('educational_level', models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD')], max_length=50)),
                ('experience_level', models.CharField(choices=[('entry_level', 'Entry Level (0-2 years)'), ('mid_level', 'Mid Level (3-5 years)'), ('senior_level', 'Senior Level (5+ years)')], max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('HS', 'High School'), ('AD', 'Associate Degree'), ('BD', "Bachelor's Degree"), ('MD', "Master's Degree"), ('PHD', 'Doctorate'), ('OT', 'Other')], max_length=100)),
                ('institution_name', models.CharField(max_length=150)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_backgrounds', to='myapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CN', 'Contract'), ('IN', 'Internship'), ('RM', 'Remote')], max_length=100)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(auto_now_add=True)),
                ('requirements', models.TextField(max_length=500)),
                ('company_name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobpost')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(db_column='job', on_delete=django.db.models.deletion.CASCADE, to='myapp.jobpost'),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('responsibilities', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='myapp.applicant')),
            ],
        ),
    ]
