# Generated by Django 5.2 on 2025-05-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(choices=[('<20000', 'Less than 20,000'), ('20000-40000', '20,000 - 40,000'), ('40000-60000', '40,000 - 60,000'), ('60000-80000', '60,000 - 80,000'), ('80000-100000', '80,000 - 100,000'), ('>100000', 'More than 100,000')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='work_hours',
            field=models.IntegerField(choices=[(1, '1-10 hours'), (2, '11-20 hours'), (3, '21-30 hours'), (4, '31-40 hours'), (5, '40+ hours')], max_length=100),
        ),
    ]
