# Generated by Django 5.2 on 2025-05-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Employer_id',
            new_name='employer_id',
        ),
    ]
