# Generated by Django 5.2 on 2025-05-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_workexperience_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalbackground',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_backgrounds', to='myapp.applicant'),
        ),
    ]
