# Generated by Django 5.2 on 2025-05-07 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_jobpost_requirements_alter_jobpost_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
