# Generated by Django 5.2 on 2025-05-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jobpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='work_hours',
            field=models.IntegerField(choices=[(1, '1-10 hours'), (2, '11-20 hours'), (3, '21-30 hours'), (4, '31-40 hours'), (5, '40+ hours')]),
        ),
    ]
