# Generated by Django 5.2 on 2025-05-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_jobpost_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(max_length=400),
        ),
    ]
