# Generated by Django 5.2 on 2025-05-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_jobpost_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='educational_level',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD')], max_length=50),
        ),
    ]
